name: Build LineageOS 22 for sapphire

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk git bc bison flex build-essential \
              curl zip unzip repo python3 python3-pip libncurses5 libncurses5-dev \
              libssl-dev ccache libtinfo5 libxml2-utils zlib1g-dev

      - name: Setup swap
        run: |
          sudo fallocate -l 10G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Initialize repo
        run: |
          mkdir lineage
          cd lineage
          repo init -u https://github.com/LineageOS/android.git -b lineage-22
          repo sync -j2 --force-sync

      - name: Clone device, vendor and kernel trees
        run: |
          cd lineage
          git clone https://github.com/TheMuppets/proprietary_vendor_xiaomi_sapphire.git -b lineage-22 vendor/xiaomi/sapphire
          git clone https://github.com/LineageOS/android_device_xiaomi_sapphire.git -b lineage-22 device/xiaomi/sapphire
          git clone https://github.com/LineageOS/android_kernel_xiaomi_sdm685.git -b lineage-22 kernel/xiaomi/sdm685

      - name: Clone GApps & Magisk
        run: |
          cd lineage
          git clone https://github.com/nikgapps/config --depth=1
          curl -L -o magisk.zip https://github.com/topjohnwu/Magisk/releases/latest/download/Magisk-v27.0.zip

      - name: Setup environment
        run: |
          cd lineage
          . build/envsetup.sh
          lunch lineage_sapphire-userdebug

      - name: Start build
        run: |
          cd lineage
          export WITH_GAPPS=true
          export TARGET_INCLUDE_Magisk=true
          mka bacon -j2

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: LineageOS-22-sapphire
          path: lineage/out/target/product/sapphire/*.zip

